#!/bin/bash

#xcode-select --install

#ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

#brew bundle
echo $(dirname $0)
for x in $(ls -d $(dirname $0)/_*); do
    ln -s $x ~/.${x##*_}
done

